[package]
name = "chi_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"
chumsky = "1.0.0-alpha.6" # playing around with the alpha
